# Generated by Django 3.2 on 2021-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
